export const REQUEST_ALL = 'MUSIC/REQUEST_ALL';
export const REQUEST_FAVORITES = 'MUSIC/REQUEST_FAVORITES';
export const SEARCH_SONGS = 'MUSIC/SEARCH_SONGS';
export const CLEAR_SONGS = 'MUSIC/CLEAR_SONGS';
export const SUCCEEDED = 'MUSIC/SUCCEEDED';
export const ERROR = 'MUSIC/ERROR';
export const SKIP = 'MUSIC/SKIP';
export const LIMIT = 'MUSIC/LIMIT';
