export const REQUEST_SONGS = 'REQUEST_SONGS';
export const REQUEST_FAVORITE_SONGS = 'REQUEST__FAVORITE_SONGS';
export const FIND_SONGS = 'FIND_SONGS';
export const RETREIVE_SONGS_SUCCESSED = 'RETREIVE_SONGS_SUCCESSED';
export const RETRIEVE_SONGS_ERROR = 'RETRIEVE_SONGS_ERROR';
export const CLEAR_SONGS = 'CLEAR_SONGS';
export const SET_SKIP = 'SET_SKIP';
export const SET_LIMIT = 'SET_LIMIT';
